steps:
  # Build the Docker image
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/react-server", "."]

  # Push the Docker image to Google Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/react-server"]

  # Create a Compute Engine instance
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "compute",
        "instances",
        "create-with-container",
        "${_INSTANCE_NAME}",
        "--machine-type",
        "${_MACHINE_TYPE}",
        "--zone",
        "${_ZONE}",
        "--container-image",
        "gcr.io/$PROJECT_ID/react-server:latest",
        "--tags",
        "http-server",
      ]
